
sudo: required
language: java

jdk:
  - oraclejdk8


script:
  - mvn clean cobertura:cobertura -Dtest=FutureTest#shouldGetFirstCompletedOfSucceedingFuturesUsingForkJoinPool -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/vavr/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "SmTmMNyC4q+c29ANQ8AcyZ/brA6jMBpcg7Xagqq02AwfnXQpHkx0IA26qHpEwym8nax89eASEhJXoMb7F4/C1Cw3KEx+ESkAWqZQoFGub7Fl1V2dF+PjD/0WIEq91Rc4bUA407SXZp67rMwOFKCKKrI6XimQEAuLUOSq3OgTu09XHj5y7OjGm+wehcs/K5dQj1hAYYX01MrGwAVu0YdAQyoCpy7lxr+XdiKPqA22Lc7Fcb7NKQiAWU9S0JdrojfXcpZK4SDCqvKVIF8h57rr6Mn8TvZi+hVdtrWAzXKGSt+/qdvau9vhFxej49UXTl7/UdyHtenpOjJZkLa29Krk/7KT7AlGbKbCrDNEWO5l543MKYzICL6ZNUvpjYHbySUoAE4Cx/Ihx/dtUcXwwm6MB74mYLTgsSuf62oRDjdWgCajiwB1gTK+g/upnrVtj+KKmY7dftxw+NZmleRDNNyJDrzmSLG9REmwDMHeicJcVQsUbBPIQ5bsmh+NVtSvag2c+SjXaHNSzMcqpeuz34Opuwm8NkhDFeFIT+LCvUgep1o0sxgphsDsvDBCwDX0GhjEmQ3j0jrbERuce2wshNTLSOF/e+tk1tXENEZHawIaSMBWLGOXVrMnuGewfFjqQ10wwCvGM8TQ7E+JrxfJYrK6+88j4bqFjO574j1IBNc3xFI="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
